language: android
jdk: oraclejdk8
sudo: false

android:
  components:
  - platform-tools
  - tools
  - build-tools-28.0.3
  - android-28
  - extra-android-support
  - extra-android-m2repository

before_install:
- chmod +x gradlew

script:
- ./gradlew clean assembleRelease --stacktrace
